[project]
name = "evaligator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "welldesignedsystem", email = "welldesignedsystem@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
evaligator = "evaligator:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
